package lenguyenthanh.facememo.data.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table CONTACT.
 */
public class Contact implements Serializable{

    private Long id;
    private String firstName;
    private String lastName;
    private String number;
    private String note;
    private String photo;
    private Integer rawContactId;

    // KEEP FIELDS - put your custom fields here

    // KEEP FIELDS END

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String firstName, String lastName, String number, String note, String photo, Integer rawContactId) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.number = number;
        this.note = note;
        this.photo = photo;
        this.rawContactId = rawContactId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Integer getRawContactId() {
        return rawContactId;
    }

    public void setRawContactId(Integer rawContactId) {
        this.rawContactId = rawContactId;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "Contact{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", number='" + number + '\'' +
                ", note='" + note + '\'' +
                ", photo='" + photo + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if(this ==  o) return true;
        if(o == null) return false;
        if(id == null) return false;
        if(!(o instanceof  Contact)) return false;
        Contact other = (Contact) o;
        return id.equals(other.id) &&
                stringEquale(firstName, other.firstName) &&
                stringEquale(lastName, other.lastName) &&
                stringEquale(number,other.number) &&
                stringEquale(photo, other.photo);
    }

    public String getName() {
        return firstName + " " + lastName;
    }

    public boolean isLocalExist(){
        return rawContactId != null;
    }

    private boolean stringEquale(String f, String l){
        if(f == null && l == null) return true;
        else if(f == null || l == null) return false;
        else return f.contentEquals(l);
    }
    // KEEP METHODS END

}
